Migrate mocking code from openbare
SUSE/Enceladus pull request #122
Opened 2017-03-01 20:57 UTC by smarlowucf

- Use pytest instead of nose tests
- Cleanup license and author information

2017-03-06 22:55 UTC, rjschwei commented on mockboto3/mockboto3/iam/models.py
> +
IAM is an acronym, thus should be used in all CAPS in this case

2017-03-06 22:57 UTC, rjschwei commented
mock [1] has a BSD license, why use MIT? Compatibility with some other code?

[1] https://pypi.python.org/pypi/mock

2017-03-07 21:02 UTC, smarlowucf commented
It's also closely correlated with the boto3 library which is under Apache license. Should the license be determined to be compatible with required packages or best fit for library itself?

2017-03-17 17:49 UTC, rjschwei requested changes

2017-03-17 17:49 UTC, rjschwei commented on mockboto3/mockboto3/iam/constants.py
> +    '-----END CERTIFICATE-----'
Convention for constants is all UPPER_CASE

2017-03-17 17:49 UTC, rjschwei commented on mockboto3/mockboto3/iam/endpoints.py
> +
should be IAM in the docstring as well

2017-03-17 17:49 UTC, rjschwei commented on mockboto3/mockboto3/iam/endpoints.py
> +    def add_user_to_group(self, kwarg):
I think convention is to use kwargs not kwarg

2017-03-17 17:49 UTC, rjschwei commented on mockboto3/mockboto3/iam/endpoints.py
> +    def _check_user_exists(self, user, method):
In the absence of any logical closeness needs please sort methods in alpha order

2017-03-17 17:49 UTC, rjschwei commented on mockboto3/tests/test_iam.py
> +
IAM

2017-04-04 17:25 UTC, rjschwei approved these changes

2017-04-04 17:25 UTC, merged