pint: add filter for 'type' attribute
SUSE/Enceladus pull request #126
Opened 2017-04-14 18:36 UTC by bear454

2017-04-14 18:50 UTC, rjschwei requested changes

2017-04-14 18:50 UTC, rjschwei commented on susePublicCloudInfoClient/setup.py
> +import version
This will surely fail. The import was in the previous location so we'd get the proper version file and not some version somewhere else

2017-04-14 18:51 UTC, rjschwei commented
Also I would have expected a test to get smt servers without filter that hen verifies that both smt-sles and smt-sap types are present. Did I miss that?

2017-04-14 21:28 UTC, bear454 commented on susePublicCloudInfoClient/setup.py
> +import version
Putting it back...

```
$ flake8
./setup.py:35:1: E402 module level import not at top of file
```

2017-04-14 21:30 UTC, bear454 commented
I think it's safe to assume that from the server tests.  The request URL isn't changing, and we're not doing any client-side manipulation outside the filters. I can add a test for it if you insist, but it feels redundant.

2017-04-14 22:16 UTC, smarlowucf commented on susePublicCloudInfoClient/setup.py
> +import version
What about an explicit execution of the version module?

```
this_path = os.path.dirname(os.path.abspath(__file__))
version_path = os.path.join(this_path, 'lib', 'susepubliccloudinfoclient', 'version.py')
execfile(version_path)

# In setup ...
version=VERSION
```

That way the python path is not being messed with, the join will use proper os.sep and flake8 remains happy.

2017-04-16 11:54 UTC, rjschwei approved these changes

2017-04-16 11:54 UTC, merged

2017-04-17 17:18 UTC, bear454 commented on susePublicCloudInfoClient/setup.py
> +import version
@smarlowucf : would you mind submitting that in a separate PR ?