ec2utils convert to Py3
SUSE/Enceladus pull request #136
Opened 2017-08-09 15:13 UTC by rjschwei

2017-08-09 21:04 UTC, smarlowucf requested changes
Looks good, just a couple imports to fix.

2017-08-09 21:04 UTC, smarlowucf commented on ec2utils/ec2uploadimg/lib/ec2utils/ec2uploadimg.py
>  #
For consistency use absolute imports. L26-27

2017-08-09 21:04 UTC, smarlowucf commented on ec2utils/ec2utilsbase/lib/ec2utils/ec2utils.py
>  from .ec2UtilsExceptions import *
Ditto absolute imports.

2017-08-10 06:34 UTC, bear454 approved these changes

2017-08-10 06:34 UTC, bear454 commented on ec2utils/ec2uploadimg/ec2uploadimg
> +                    'Could not reliable determine the ',
TODO: replace "reliable" with "reliably" (not really apropos to this PR - just noticed it.)

2017-08-10 13:37 UTC, smarlowucf approved these changes

2017-08-10 13:43 UTC, merged