- gcemetadata
SUSE/Enceladus pull request #139
Opened 2017-08-14 19:36 UTC by rjschwei

+ Add a man page

2017-08-22 17:06 UTC, rjschwei commented
@jbyers-suse @joelgordon  would you please read the man page and see if this makes sense to you. Thanks,

2017-08-23 22:10 UTC, bear454 requested changes

2017-08-23 22:10 UTC, bear454 commented on gcemetadata/man/man1/gcemetadata.1
> +https://cloud.google.com/compute/docs/storing-retrieving-metadata. The
I recommend leaving a space between the URL and the period at the end of the sentence, as including the period in the URL results in a 404 NOT FOUND.

2017-08-23 22:10 UTC, bear454 commented on gcemetadata/man/man1/gcemetadata.1
> +command line options the tool accepts are for the most part dynamically and
"for the most part dynamically and" ?
Something's missing here.

2017-08-23 22:10 UTC, bear454 commented on gcemetadata/man/man1/gcemetadata.1
> +.I unavailable.
Consider `.IR unavailable .`

2017-08-23 22:10 UTC, bear454 commented on gcemetadata/man/man1/gcemetadata.1
> +.I standard.
Consider `.IR standard .` as the period is not part of the supported value.

2017-08-23 22:10 UTC, bear454 commented on gcemetadata/man/man1/gcemetadata.1
> +.I instance.
Consider `.IR instance .`

2017-08-23 22:10 UTC, bear454 commented on gcemetadata/man/man1/gcemetadata.1
> +Print he version of the tool.
s/he/the/

2017-08-23 22:10 UTC, bear454 commented on gcemetadata/man/man1/gcemetadata.1
> +.I unavailable.
`.IR unavailable .`

2017-08-25 17:07 UTC, merged