- gcemetadata
SUSE/Enceladus pull request #144
Opened 2017-08-16 19:59 UTC by rjschwei

+ Properly handle overlapping names for API access such as "id" which
    is used as instance id but also as license id.
  + Properly handle the license access path, this also fixes and issue
    with a traceback occurring with gcemetadata on on-demand instances that
    have a license

2017-08-16 22:09 UTC, smarlowucf requested changes

2017-08-16 22:09 UTC, smarlowucf commented on gcemetadata/gcemetadata
> +                    continue
These are preexisting but the continue's don't do anything functionally since all clauses are part of the same if/elif. Makes reading the code a bit confusing.

2017-08-16 22:09 UTC, smarlowucf commented on gcemetadata/lib/gcemetadata/gcemetadata.py
> +        self.default_license_id = '0'
Nit-picky but to match the alpha order default_license_id should be above defaultDiskID.

2017-08-16 22:09 UTC, smarlowucf commented on gcemetadata/lib/gcemetadata/gcemetadata.py
> +    def query_all_sub_options(self, on_off=False):
on_off kwarg not used

2017-08-16 22:09 UTC, smarlowucf commented on gcemetadata/lib/gcemetadata/gcemetadata.py
> +        if not license_id in known_ids:
`if license_id not in known_ids` is nicer to read.

2017-08-16 22:09 UTC, smarlowucf commented on gcemetadata/lib/gcemetadata/gcemetautils.py
> +        for l_opts in license_opts:
s/l_opts/l_opt

2017-08-16 22:21 UTC, rjschwei commented on gcemetadata/gcemetadata
> +                    continue
Oops debug leftover good catch

2017-08-16 22:22 UTC, rjschwei commented on gcemetadata/lib/gcemetadata/gcemetadata.py
> +        self.default_license_id = '0'
Not after pep8 clean up, still coming....

2017-08-17 12:20 UTC, smarlowucf approved these changes

2017-08-17 12:40 UTC, jgleissner commented on gcemetadata/lib/gcemetadata/gcemetadata.py
> +        self.license_data_shown
``self.license_data_shown`` statement looks incomplete

2017-08-17 13:37 UTC, merged