- ec2metadata
SUSE/Enceladus pull request #156
Opened 2017-09-19 15:54 UTC by rjschwei

+ Port to Python 3

2017-09-19 19:12 UTC, smarlowucf requested changes

2017-09-19 19:12 UTC, smarlowucf commented on ec2utils/ec2metadata/lib/ec2metadata/ec2metautils.py
> +        if close_file:
Can drop this.

2017-09-19 19:12 UTC, smarlowucf commented on ec2utils/ec2metadata/lib/ec2metadata/ec2metautils.py
> +    if close_file:
And put this inside finally clause.

2017-09-20 00:15 UTC, bear454 commented
I don't have anything constructive to add.

2017-09-20 13:27 UTC, merged