Use validate method to validate share-with arg.
SUSE/Enceladus pull request #178
Opened 2018-01-09 23:02 UTC by smarlowucf

This is minor given it's an error case but any value thrown at the current regex yields an instance of _sre.SRE_Match. Thus it always evaluates to True.

Tried making a suitable regex but after fighting with it I chose to just use Python split with a separate validate function.

Given the use of split maybe this should be re-worked more to store the validated and split list so it doesn't have to be parsed twice. Also, the validate function could be added to the generic utils file instead of creating a new one for publish.

2018-01-10 13:18 UTC, rjschwei requested changes

2018-01-10 13:18 UTC, rjschwei commented on ec2utils/ec2publishimg/lib/ec2utils/ec2publishimg_utils.py
> +def validate_accounts(self, share_with):
This should be validate_account_numbers, we do not validate the account.

2018-01-10 13:18 UTC, rjschwei commented on ec2utils/ec2publishimg/ec2publishimg
> +from ec2utils.ec2publishimg_utils import validate_accounts
Nope, not doing this. Either validate_account_numbers moves directly into this code or into utilsutils

2018-01-11 16:12 UTC, smarlowucf commented
Re-based with changes.

2018-01-12 14:21 UTC, rjschwei approved these changes

2018-01-12 14:21 UTC, merged